In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("wine.csv")

In [3]:
dataset   #3 wines means 3outputs 3 y
#y1 y2 y3   multiclass categorical var  prob percentage

,Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [5]:
y= dataset["Wine"]

In [6]:
y

0      1
1      1
2      1
3      1
4      1
      ..
173    3
174    3
175    3
176    3
177    3
Name: Wine, Length: 178, dtype: int64

In [9]:
y_cat = pd.get_dummies(y)  #multicolinearity issue is not in y no need to drop in this like x1 x2..

In [10]:
y_cat

     1  2  3
0    1  0  0
1    1  0  0
2    1  0  0
3    1  0  0
4    1  0  0
..  .. .. ..
173  0  0  1
174  0  0  1
175  0  0  1
176  0  0  1
177  0  0  1

[178 rows x 3 columns]

In [11]:
dataset.columns

Index(['Wine', 'Alcohol', 'Malic.acid', 'Ash', 'Acl', 'Mg', 'Phenols',
       'Flavanoids', 'Nonflavanoid.phenols', 'Proanth', 'Color.int', 'Hue',
       'OD', 'Proline'],
      dtype='object')

In [34]:
X = dataset.drop("Wine",axis=1)

In [35]:
X

,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [36]:
X.shape

(178, 13)

In [17]:
from keras.models import Sequential

In [18]:
model = Sequential()

In [19]:
from keras.layers import Dense

In [21]:
model.get_config()

{'name': 'sequential', 'layers': []}

In [23]:
model.add(Dense (
                 kernel_initializer='zeros',
                  units=4,
                  input_shape=(13,),
                  activation='relu',
                  bias_initializer='zeros'
    
))

In [25]:
model.get_config()

{'name': 'sequential',
 'layers': [{'class_name': 'InputLayer',
   'config': {'batch_input_shape': (None, 13),
    'dtype': 'float32',
    'sparse': False,
    'ragged': False,
    'name': 'dense_input'}},
  {'class_name': 'Dense',
   'config': {'name': 'dense',
    'trainable': True,
    'dtype': 'float32',
    'batch_input_shape': (None, 13),
    'units': 4,
    'activation': 'relu',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'Zeros', 'config': {}},
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'activity_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None}}]}

In [26]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 4)                 56

=================================================================
Total params: 56
Trainable params: 56
Non-trainable params: 0
_________________________________________________________________

In [27]:
model.add(Dense (
                 kernel_initializer='zeros',
                  units=5,
                  activation='relu',
                  bias_initializer='zeros'
    
))

In [28]:
model.get_config()

{'name': 'sequential',
 'layers': [{'class_name': 'InputLayer',
   'config': {'batch_input_shape': (None, 13),
    'dtype': 'float32',
    'sparse': False,
    'ragged': False,
    'name': 'dense_input'}},
  {'class_name': 'Dense',
   'config': {'name': 'dense',
    'trainable': True,
    'dtype': 'float32',
    'batch_input_shape': (None, 13),
    'units': 4,
    'activation': 'relu',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'Zeros', 'config': {}},
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'activity_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None}},
  {'class_name': 'Dense',
   'config': {'name': 'dense_1',
    'trainable': True,
    'dtype': 'float32',
    'units': 5,
    'activation': 'relu',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'Zeros', 'config': {}},
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'activity_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None}}]}

In [29]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 4)                 56

 dense_1 (Dense)             (None, 5)                 25

=================================================================
Total params: 81
Trainable params: 81
Non-trainable params: 0
_________________________________________________________________

In [30]:
model.add(Dense (
                 kernel_initializer='zeros',
                  units=3,
                  activation='softmax',
                  bias_initializer='zeros'
    
))

In [31]:
model.get_config()

{'name': 'sequential',
 'layers': [{'class_name': 'InputLayer',
   'config': {'batch_input_shape': (None, 13),
    'dtype': 'float32',
    'sparse': False,
    'ragged': False,
    'name': 'dense_input'}},
  {'class_name': 'Dense',
   'config': {'name': 'dense',
    'trainable': True,
    'dtype': 'float32',
    'batch_input_shape': (None, 13),
    'units': 4,
    'activation': 'relu',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'Zeros', 'config': {}},
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'activity_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None}},
  {'class_name': 'Dense',
   'config': {'name': 'dense_1',
    'trainable': True,
    'dtype': 'float32',
    'units': 5,
    'activation': 'relu',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'Zeros', 'config': {}},
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'activity_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None}},
  {'class_name': 'Dense',
   'config': {'name': 'dense_2',
    'trainable': True,
    'dtype': 'float32',
    'units': 3,
    'activation': 'softmax',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'Zeros', 'config': {}},
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'activity_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None}}]}

In [32]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 4)                 56

 dense_1 (Dense)             (None, 5)                 25

 dense_2 (Dense)             (None, 3)                 18

=================================================================
Total params: 99
Trainable params: 99
Non-trainable params: 0
_________________________________________________________________

In [33]:
model.compile(loss="categorical_crossentropy")

In [37]:
model.fit(X,y_cat,epochs=20)  #AFTER RUNNING FIRST EPOCHS ;FROM SCND BIAS AND WEIGHT WILL RUN FROM THE NEXT VALUE

Epoch 1/20
6/6 [==============================] - 1s 4ms/step - loss: 1.0983
Epoch 2/20
6/6 [==============================] - 0s 5ms/step - loss: 1.0976
Epoch 3/20
6/6 [==============================] - 0s 3ms/step - loss: 1.0970
Epoch 4/20
6/6 [==============================] - 0s 3ms/step - loss: 1.0965
Epoch 5/20
6/6 [==============================] - 0s 4ms/step - loss: 1.0962
Epoch 6/20
6/6 [==============================] - 0s 2ms/step - loss: 1.0957
Epoch 7/20
6/6 [==============================] - 0s 3ms/step - loss: 1.0954
Epoch 8/20
6/6 [==============================] - 0s 6ms/step - loss: 1.0950
Epoch 9/20
6/6 [==============================] - 0s 1ms/step - loss: 1.0946
Epoch 10/20
6/6 [==============================] - 0s 3ms/step - loss: 1.0943
Epoch 11/20
6/6 [==============================] - 0s 3ms/step - loss: 1.0940
Epoch 12/20
6/6 [==============================] - 0s 4ms/step - loss: 1.0937
Epoch 13/20
6/6 [==============================] - 0s 3ms/step - loss: 1.0934
Epoch 14/20
6/6 [==============================] - 0s 3ms/step - loss: 1.0930
Epoch 15/20
6/6 [==============================] - 0s 6ms/step - loss: 1.0927
Epoch 16/20
6/6 [==============================] - 0s 6ms/step - loss: 1.0924
Epoch 17/20
6/6 [==============================] - 0s 3ms/step - loss: 1.0921
Epoch 18/20
6/6 [==============================] - 0s 3ms/step - loss: 1.0919
Epoch 19/20
6/6 [==============================] - 0s 3ms/step - loss: 1.0917
Epoch 20/20
6/6 [==============================] - 0s 6ms/step - loss: 1.0914

In [ ]:
import seaborn as sns

In [ ]:
#sns.scatterplot(data=dataset, x="Class")